### PR TITLE
restructure `views/DexPage` & code review nits

### PR DESCRIPTION
**Pull request by amass01**

### CODE REVIEW

**Comment by alexlyp** [comment]
Need to add 
    isValid,
    error,
    onGetConfigDex,
    addr,
    setAddress
 to be exported by the RegisterPage hook.

**Comment by amass01** [comment]
@alexlyp oh, nice catch; done.

**Comment by alexlyp** [comment]
SetNewPassphraseModal is throwing "onSubmit" is not a function from line:23 from its hooks.js

**Comment by alexlyp** [comment]
Cancel button on the SetNewPassphraseModal isn't working any more

**Comment by amass01** [comment]
> SetNewPassphraseModal is throwing "onSubmit" is not a function from line:23 from its hooks.js

Fixed.

**Pull request merged**
